### PR TITLE
Fix unauthorized endpoints and made use of @Authorized consistent

### LINKED ISSUE #48: Bug: Fix unauthorized endpoints and use @Authorized annotation where applicable
Some endpoints are currently authorized.

We should also use @Authorized wherever we can.

### PR DESCRIPTION
**Pull request by jonaslanglotz**
Resolves #48

### CODE REVIEW

File: server/src/resolvers/user/logout.ts [hunk 1]
```diff
@@ -1,10 +0,0 @@
-import { Context } from '../../types'
-
-export async function logoutUser ({ req }: Context) : Promise<void> {
-  console.log(req.session)
-  await new Promise<void>((resolve) => {
-    req.session.destroy(resolve)
-  })
-
-  console.log(req.session)
-}
```
Comment (EricZimmer1) [inline server/src/resolvers/user/logout.ts:10]: We don't need that anymore?

**Review by EricZimmer1 — COMMENTED** [review]
Looks good to me, just a quick Question about the delete of logout.

File: server/src/resolvers/user/logout.ts (hunk 1 above)
Comment (jonaslanglotz) [reply server/src/resolvers/user/logout.ts:10]: I moved it into the resolver itself, same as self.ts

**Review by EricZimmer1 — APPROVED** [review]

**Review by bucherfa — APPROVED** [review]
